### PR TITLE
Vector Addition Resize

### PR DESCRIPTION
**Pull request by pwolfert**

### CODE REVIEW

**Comment by pandafulmanda** [comment]
hehehe the new graphics are great

**Comment by pandafulmanda** [comment]
I'm guessing you're not done resizing yet?  I'm getting that weird space at the bottom again.

screen shot 2015-06-09 at 10 15 44 am
screen shot 2015-06-09 at 10 15 46 am

**Comment by pandafulmanda** [comment]
should I go ahead and merge this, and additional changes will be on a new PR, @pwolfert ?

**Comment by pwolfert** [comment]
@pandafulmanda It shouldn't look like this. I'll look into it. It's supposed to look like this

short

**Comment by pwolfert** [comment]
Ah, I see that the top bar was using the bootstrap grid classes for its spacing, which means when you make the window skinny enough, it goes into a "mobile" mode.  I'll swap those out those classes.

**Pull request merged**
